<?xml version="1.0"?>
<package format="3">
  <name>px4_real_flight</name>
  <version>0.0.1</version>
  <description>PX4 real flight with MAVROS2 for position mode using FAST-LIO2 external vision</description>
  <maintainer email="uav@uav.com">uav</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>mavros_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
